apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesRelease
metadata:
  name: v1.19.3---vmware.1
  namespace: tkr-system
  labels:
    v1: ""
    v1.19: ""
    v1.19.3: latest
    v1.19.3---vmware: latest
    v1.19.3---vmware.1: latest
spec:
  version: 1.19.3+vmware.1

  kubernetesVersion: 1.19.3+vmware.1

  repository: vmware.io

  images:
  - name: coredns
    repository: vmware.io  # optional (default: top level repository)
    tag: v1.6.5_vmware.2
  - name: etcd
    tag: v3.3.15_vmware.4

  nodeImageRef:
    apiVersion: vmoperator.vmware.com/v1alpha1
    kind: VirtualMachineImage
    name: photon-3-k8s-v1.19.3---vmware.1

status:
  conditions:
  - type: UpdateAvailable
    status: True
    message: a TKR with a later version is available
  - type: Compatible
    status: True
