#@data/values
#@overlay/match-child-defaults missing_ok=True

---
infraProvider: vsphere
antrea:
  config:
    serviceCIDR: 10.96.0.0/12
    trafficEncapMode: encap
    noSNAT: false
    featureGates:
      AntreaProxy: false
      AntreaPolicy: true
      AntreaTraceflow: false
      FlowExporter: false
      NetworkPolicyStats: false
  image:
    repository: docker.io
    path: antrea/antrea-ubuntu 
    tag: v0.11.1
    pullPolicy: IfNotPresent
