# permissions for end users to view contexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: context-viewer-role
rules:
- apiGroups:
  - client.tanzu.vmware.com
  resources:
  - contexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - client.tanzu.vmware.com
  resources:
  - contexts/status
  verbs:
  - get
