# permissions for end users to edit cspconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cspconfig-editor-role
rules:
- apiGroups:
  - auth.tanzu.vmware.com
  resources:
  - cspconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.tanzu.vmware.com
  resources:
  - cspconfigs/status
  verbs:
  - get
