#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cloud-provider-vsphere-credentials"}})
#@yaml/text-templated-strings
---
#@overlay/replace
stringData:
  (@=values.vsphereCPI.server@).username: (@=values.vsphereCPI.username@)
  (@=values.vsphereCPI.server@).password: (@=values.vsphereCPI.password@)

#@ if values.vsphereCPI.nsxt.secretName != '' and values.vsphereCPI.nsxt.secretNamespace != '' and values.vsphereCPI.nsxt.username != '' and values.vsphereCPI.nsxt.password != '':
#@overlay/match by=overlay.subset({"kind": "Secret"})
#@overlay/append
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ values.vsphereCPI.nsxt.secretName
  namespace: #@ values.vsphereCPI.nsxt.secretNamespace
stringData:
  username: #@ values.vsphereCPI.nsxt.username
  password: #@ values.vsphereCPI.nsxt.password
type: Opaque
#@ end
