#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: null
tkg_cluster_role: null
pinniped:
  cert_duration: 2160h
  cert_renew_before: 360h
  supervisor_svc_endpoint: "https://0.0.0.0:31234" #! Do not change. Will be updated by post-deployment job. This is used to configure jwtAuthenticator
  supervisor_ca_bundle_data: "ca_bundle_data_of_pinniped_supervisor_svc" #! Do not change. Will be updated by post-deployment job. This is used to configure jwtAuthenticator to communicate with supervisor svc
  supervisor_svc_external_ip: null #! provide if the node IP or LB IP of Pinniped supervisor service is known, otherwise leave it empty. e.g. 10.165.123.84
  supervisor_svc_external_dns: null #! provide if the LB DNS of Pinniped supervisor service is known, otherwise leave it empty. e.g pinniped-svc.us-west-2a.com
  upstream_oidc_provider_name: "dex" #! the name of upstream oidc provider. Default is dex, since Dex is deployed as the upstream of Pinniped
  upstream_oidc_client_id: "" #! the client secret used to talk to Dex
  upstream_oidc_client_secret: "" #! the client secret used to talk to Dex
  upstream_oidc_issuer_url: "https://0.0.0.0:30167" #! the upstream oidc issuer url. It should be pointed to Dex service, since Dex is deployed as the upstream of Pinniped. e.g https://endpoint-points-to-dex:5443
  upstream_oidc_tls_ca_data: null #! this tls ca data is used to communicate with upstream_oidc_issuer_url
  image:
    name: pinniped
    tag: v0.3.0_vmware.1
    repository: registry.tkg.vmware.run
    pull_policy: IfNotPresent
  post_deploy_job_image:
    name: tkg-pinniped-post-deploy
    tag: v0.3.0_vmware.1
    repository: registry.tkg.vmware.run
    pull_policy: Always
dex:
  app: dex
  create_namespace: true
  namespace: tanzu-system-auth
  organization: vmware
  commonname: tkg-dex
  config:
    frontend:
      theme: tkg
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    expiry:
      signingKeys: 10m
      idTokens: 5m
    logger:
      level: debug
      format: json
    connector: null  #! dex config should be either oidc or ldap
    issuerPort: "30167" #! requred only for MGMT_CLUSTER_VIP if provider is vsphere. Default is "30167"
    oidc:
      CLIENT_ID: null #! required if oidc enabled
      CLIENT_SECRET: null #! required if oidc enabled
      issuer: null #! <OIDC_IDP_URL> is required if oidc enabled
      clientID: $OIDC_CLIENT_ID  #! do not change this
      clientSecret: $OIDC_CLIENT_SECRET #! do not change this
      basicAuthUnsupported: null
      insecureEnableGroups: null
      insecureSkipEmailVerified: true
      getUserInfo: null
      userIDKey: null
      userNameKey: null
      claimMapping: {}
    ldap:
      host: null #! <LDAP_HOST> is required if ldap enabed
      insecureNoSSL: null
      startTLS: null
      rootCA: null #! <rootCA> or <rootCAData> if required when LDAP host is using self signed certificate. Path to the CA file
      rootCAData: null #! <rootCA> or <rootCAData> if required when LDAP host is using self signed certificate. Actual CA bundle
      bindDN: null #! <bindDN> is required when host doesn't support anonymous authentication
      bindPW: null #! <bindPW> is required when host doesn't support anonymous authentication
      usernamePrompt: LDAP Username
      insecureSkipVerify: False
      userSearch:
        baseDN: null #! required if ldap userSearch enabled
        filter: "(objectClass=posixAccount)"
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: givenName
      groupSearch:
        baseDN: null  #! required if ldap groupSearch enabled
        filter: "(objectClass=posixGroup)"
        userAttr: uid
        groupAttr: memberUid
        nameAttr: cn
    oauth2:
      skipApprovalScreen: true
    storage:
     type: kubernetes
     config:
       inCluster: true     
    enablePasswordDB: false
  service:
    name: dexsvc
    type: null
  deployment:
    replicas: 1
  certificate: 
    duration: 2160h
    renewBefore: 360h
  image:
    name: dex
    tag: v2.22.0_vmware.2
    repository: registry.tkg.vmware.run
    pullPolicy: IfNotPresent
